### ISSUE TITLE
ServerReplyURL 沒有回傳任何東西？

### ISSUE THREAD

**Issue by asys0512** [ECPay/ECPayAIO_PHP#11]
我發現「ServerReplyURL」並沒有打到我伺服器的行為，我是使用 127.0.0.1 在本地測試的，還是說回傳的不是 POST 是 json 格式呢？

使用的是
https://github.com/ECPay/ECPayAIO_PHP/blob/master/PayLogisticSDK/example/sample_BGHomeCreateShippingOrder.php

我是在ＡＰＩ文件第六點
https://www.ecpay.com.tw/Content/files/ecpay_030.pdf
不管是用ＰＯＳＴ、ＧＥＴ都不行！好像根本沒打過來一樣

**Comment by AllennChang** [comment]
您好, 我們回傳的位置要有對外ip的伺服器才行, 請確認您設定的ServerReplyURL 有對外ip或domain 且接收的port 為80  或443

**Comment by mypetertw** [comment]
了解，謝謝
再問些題外話
CheckMacValue 是必須的嗎？
因為我目前沒有這個值，但是沒有報錯

以及
https://github.com/ECPay/ECPayAIO_PHP/blob/master/PayLogisticSDK/example/sample_BGHomeCreateShippingOrder.php
這些範例要如何識別正式還測試環境呢

**Comment by AllennChang** [comment]
物流 sdk 用 mid 就能識別 我們已設定好, 會自動判斷

**Comment by mypetertw** [comment]
再請問一下
為什麼 ServerReplyURL 中我把 ＰＯＳＴ丟到ＳＥＳＳＩＯＮ裡面，但還是無法在其他頁被使用（ＮＵＬＬ的）？

**Comment by AllennChang** [comment]
您好, 不懂您的意思,若有串接的問題可以寫信到 techsupport@ecpay.com.tw ,我們會有專員幫您回覆

**Comment by mypetertw** [comment]
已寄信給 techsupport@ecpay.com.tw

**Comment by mypetertw** [comment]
想問一下假設訂單狀態改變，他都會打我設定的 ServerReplyURL ？我想問一下這是不是我想像的這樣。我是打 order create 這隻（ＡＰＩ第六點），我成立訂單才會打這隻通知你們，那ＡＰＩ提到的「物流狀態都會透過此 URL 通知。」是指他會記住我的 ServerReplyURL，當你們那邊物流狀態有變，就會自動打這隻ＡＰＩ，我就不需要再另外打ＡＰＩ去確認物流狀態？（ＡＰＩ文件上好像也沒有這種ＡＰＩ）

**Comment by AllennChang** [comment]
> 想問一下假設訂單狀態改變，他都會打我設定的 ServerReplyURL ？我想問一下這是不是我想像的這樣。我是打 order create 這隻（ＡＰＩ第六點），我成立訂單才會打這隻通知你們，那ＡＰＩ提到的「物流狀態都會透過此 URL 通知。」是指他會記住我的 ServerReplyURL，當你們那邊物流狀態有變，就會自動打這隻ＡＰＩ，我就不需要再另外打ＡＰＩ去確認物流狀態？（ＡＰＩ文件上好像也沒有這種ＡＰＩ）

=>您好 ,是的, 若物流狀態變更我們會主動通知您設定的 ServerReplyURL

**Comment by asys0512** [comment]
抱歉我有寄信給 techsupport@ecpay.com.tw 但沒回，因此我先在這裡問～～
我剛下載物流狀態代碼ＥＸＣＥＬ，CVS的 UNIMART 哪一個是代表已出貨跟已完成啊？

**Comment by asys0512** [comment]
以及ＡＰＩ第五個，電子地圖，似乎沒有手機版？上面寫說已經整合，預設帶ＰＣ就好，但似乎沒有手機版呢

**Comment by AllennChang** [comment]
> CVS的 UNIMART 哪一個是代表已出貨跟已完成啊？好像都是錯誤代碼？
> HOME的TCAT 的已出貨跟已完成是哪個代碼？

CVS的 UNIMART 哪一個是代表已出貨跟已完成啊？
>已出貨：2030 物流中心驗收成功
>已完成：2067 消費者成功取件

HOME的TCAT 的已出貨跟已完成是哪個代碼？
>已出貨：3001 轉運中(即集貨)
>已完成：3003 配完

**Comment by AllennChang** [comment]
> 個，電子地圖，似乎沒有手機版？上面寫說已經整合，預設帶ＰＣ就好，但似乎沒

只有全家超商電子地圖不用特別選, 統一超商的還是要選喔

**Comment by asys0512** [comment]
CVS的 UNIMART 哪一個是已退貨代碼？
是 4002 嗎
HOME的TCAT 哪一個是已退貨代碼？
是 5008 嗎

**Comment by AllennChang** [comment]
您好, 詳細串接問題請寫信到 techsupport@ecpay.com.tw ,我們會有專員幫您回覆
