### ISSUE TITLE
可以建立composer package嗎?

### ISSUE THREAD

**Issue by natsumework** [ECPay/ECPayAIO_PHP#12]
您好：  
希望可以建立composer package, 方便安裝跟管理版本

**Comment by AllennChang** [comment]
您好, 感謝您的建議, 我會反應給開發團隊進行評估,

**Comment by fdjkgh580** [comment]
@AllennChang 您好，目前準備要接貴公司的 ＡＰＩ
我看這個 issue 已經過蠻久的，請問後續有進展嗎？

**Comment by AllennChang** [comment]
@fdjkgh580  您好, 我們開發團隊已有規劃安排, 但近期還尚未排入開發時程,  若近期要串接建議您先用目前的sdk 版本,未來完成建立composer package後我們會第一時間上架, 感謝您的詢問,
