### ISSUE TITLE
手機選超商會出現錯誤。

### ISSUE THREAD

**Issue by l7263626** [ECPay/ECPayAIO_PHP#15]
15d1895c2841d 的修改會造成手機選超商出現錯誤 call to undefined method EcpayLogistics::IsLegalValue()

**Comment by AllennChang** [comment]
您好, 感謝你的反應, 我們會回報開發團隊

**Comment by AllennChang** [comment]
您好, 我們己修正完成, 若有任何問題 煩請再跟我們反應, 感謝
