### ISSUE TITLE
B2C電子發票介接文件開立發票參數拼字問題

### ISSUE THREAD

**Issue by CarlLee1983** [ECPay/ECPayAIO_PHP#18]
開立發票中的參數，在文件中載具類別編號分別是 CarrierType 與 CarrierNum，但 SDK 中是 CarruerType 與 CarruerNum，看起來 Carrier 應該是筆誤

**Comment by AllennChang** [comment]
您好, 抱歉現在才回覆你的問題,  在SDK內用的參數是舊版規格的參數名稱, 請參考
https://github.com/ECPay/ECPayAIO_PHP/blob/master/EInvoiceSDK/B2C%E9%9B%BB%E5%AD%90%E7%99%BC%E7%A5%A8%E4%BB%8B%E6%8E%A5%E6%8A%80%E8%A1%93%E6%96%87%E4%BB%B6.pdf
若有任何問題, 請再跟我們反應, 感謝
