### ISSUE TITLE
AIO PHP 建議：SDK 的 Items 增加 Key Name 判斷

### ISSUE THREAD

**Issue by KJ-Chiu** [ECPay/ECPayAIO_PHP#20]
## 程式參考
* 範例中的 Items 陣列包含 Key Name `Name` `Price` `Currency` `Quantity`
https://github.com/ECPay/ECPayAIO_PHP/blob/5087fb9993ebaf1b795cfdc6840930c98c68b0a1/AioSDK/example/sample_Credit_CreateOrder.php#L30-L32

* SDK 中轉換的方式卻是使用 array 的方法轉為字串
https://github.com/ECPay/ECPayAIO_PHP/blob/5087fb9993ebaf1b795cfdc6840930c98c68b0a1/AioSDK/sdk/ECPay.Payment.Integration.php#L1151-L1158

## 可能遇到問題
* 如果 `Name` `Price` `Currency` `Quantity` 在程式端指定的順序跟範例不一樣時，會造成字串顯示與預期不符
  * ex `['Name' => 'TEST', 'Price' => 100, 'Quantity' => 1, 'Currency' => '元']` 會變成 `TEST 100 1  x 0`

## 建議
1. SDK 中分別判斷上述四個名稱以產生最終結果或丟出錯誤訊息
2. 文件中說明以上四個名稱需要按照順序指派

以上為實作時剛好遇到的問題給個心得，
也希望對剛好有遇到類似問題的開發者有所幫助～

**Comment by AllennChang** [comment]
您好, 感謝您的建議, 我們會反應給開發團隊,  若有任何問題 請隨時在跟我們反應, 感謝
