### ISSUE TITLE
你們的效率都那麼差嗎？

### ISSUE THREAD

**Issue by fiddler0305** [ECPay/ECPayAIO_PHP#4]
**2016/12/9** 的 pull requests  [https://github.com/ECPay/ECPayAIO_PHP/pull/2](https://github.com/ECPay/ECPayAIO_PHP/pull/2) 沒鳥我，打電話反應還是一樣

**2017/6/12** 才更新萊爾富不支援問題

都 pull request了，改一下很困難嗎？
誇張！

**Comment by AllennChang** [comment]
很抱歉 ,之前pull requests 沒有通知到, 所以未即時處理, 我們深感抱歉, 未來有新的pull requests 我們會立即反應給我們的開發團隊, 謝謝您的回饋及反應
