### ISSUE TITLE
開立發票問題

### ISSUE THREAD

**Issue by JimRoid** [ECPay/ECPayAIO_PHP#5]
最近開立電子發票有時會收到下面問題

6:CustomerIdentifier

12:CustomerIdentifier

想請問是什麼原因造成的

每次補開發票都很辛苦

**Comment by JimRoid** [comment]
Ecpay_Invoice.php

版本:V1.0.0315

回寫資料表會變成這樣

請問是否有開發票成功還是什麼其他的問題

![2018-04-12 9 40 57](https://user-images.githubusercontent.com/2839452/38651898-245d9a12-3e36-11e8-9419-757568b7c3f6.png)
![2018-04-12 9 41 07](https://user-images.githubusercontent.com/2839452/38651900-2487f668-3e36-11e8-8a1d-e0ecf7f8a941.png)

**Comment by AllennChang** [comment]
感謝你的反應, 我已把您的問題反應給客服團隊協助確認,

**Comment by AllennChang** [comment]
您好, 請你把相關問題資訊反應到  techsupport@ecpay.com.tw 信箱, 我們會由專人為您服務, 謝謝您
