### ISSUE TITLE
驗證規則異常

### ISSUE THREAD

**Issue by RYRDU** [ECPay/ECPayAIO_PHP#7]
在 ECPay.Logistics.Integration.php 中所使用的正規式規則 ``/[\^\'`\!＠#%&\*\+\\\"<>\|_\[\]]+/`` 會造成部份中文字元判斷異常，而導致驗證不通過，因為規則中使用了全形`@`而導致

**Comment by AllennChang** [comment]
您好, 感謝您反應的問題, 我會提供給開發團隊進行評估 ,若有任何更新, 會再發布版本在這目錄, 再次感謝您的反應問題,
