### ISSUE TITLE
可以協助建立版本號嗎？

### ISSUE THREAD

**Issue by cobenash** [ECPay/ECPayAIO_PHP#8]
在以下的SDK中，沒有對應的版本號，建議建立版本號，可以在第三方整合套件中，有一定程度的幫助
https://github.com/ECPay/ECPayAIO_PHP/blob/master/AioSDK/sdk/ECPay.Payment.Integration.php

**Comment by AllennChang** [comment]
收到, 感謝您的提醒, 我近期會找開發團隊討論這個議題, 若有任何更新, 會再回覆通知, 再次謝謝您的建議

**Comment by AllennChang** [comment]
您好, 目前已有在sdk中增加版本號, 再次感謝您的反應
