### ISSUE TITLE
驗證 CustomerIdentifier 正規化變數錯誤

### ISSUE THREAD

**Issue by ohyeahyao** [ECPay/ECPayAIO_PHP#9]
您好

在 check_invoiceString 這個 function 中，正規化驗證 CustomerIdentifier 的變數是否有誤

`$arParameters` 這個變數不屬於這個 function 裡的 

是否需要將  
https://github.com/ECPay/ECPayAIO_PHP/blob/24bad580649bf0a30f751956943e53c91d72c417/AioSDK/sdk/ECPay.Payment.Integration.php#L1203

改為
```
if (!preg_match('/^[0-9]{8}$/', $arExtend['CustomerIdentifier'])) {
```

**Comment by AllennChang** [comment]
您好, 感謝您反應的問題, 我們將把問題轉由開發單位評估處理

**Comment by AllennChang** [comment]
您好, 我們已完修正, 再次感謝您的反應
